[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dispatcher"
version = "2.2.1"
description = "Despacha mensagens entre dispositivos de acordo com o protocolo."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Thales Martins", email = "thalesdiniz30@gmail.com"},
    { name = "Kerlon Ribeiro", email = "mitokerlon1227@gmail.com"}
]

# Dependências do projeto (passando o requirements.txt para cá)
dependencies = [
    # Libs de Configurações
    "pyyaml",
    "pydantic",
    "pydantic-settings",

    # Libs de Protocolos
    "pyserial",
    "pyserial-asyncio",

    # Persistência dos dados
    "aiosqlite",

    # API e Servidor Web
    "fastapi",
    "uvicorn",
    "websockets",
]

# Comando para rodar a bifas
[project.scripts]
bifrost = "dispatcher.__main__:main"

[tool.setuptools.packages.find]
include = ["dispatcher"]