
[paths]
device_registry = "config/devices.json"
logger_config = "config/logs.toml"

[uart]
ports = [
  "/dev/ttyS0",
  "/dev/ttyAMA2",
  "/dev/ttyAMA3", # ESP-NOW
  "/dev/ttyAMA4",
  "/dev/ttyAMA5"  # LoRa
]
baud_rate = 9600

# Configurações do broker MQTT
[mqtt]
broker = "localhost"
port = 1883