
device_registry: "devices.json"
logger_config: "logs.yaml"

lora:
  baudrate: 9600 

#espnow:
#  port: "/dev/ttyAMA2" 
#  baudrate: 9600

#mqtt:
#  hosst: "localhost"
#  port: 1883

#database:
#  host:
#  port:
#  user:
#  db:
#  password:
#  url: