
logger_config_path: "logs.yaml"

registry_db_path: "db/devices.db"
registry_db_schema_path: "db/schema.sql"

rest_api:
  host: "0.0.0.0"
  port: 8000
  db_path: "config/db/devices.db"

lora:
  port: "/dev/pts/11"
  baudrate: 9600

espnow:
  port: "/dev/ttyAMA2" 
  baudrate: 9600

#mqtt:
#  hosst: "localhost"
#  port: 1883

#database:
#  host:
#  port:
#  user:
#  db:
#  password:
#  url: