
[paths]
device_registry = "config/devices.json"
logger_config = "config/logs.toml"

[uart]
ports = [
  "/dev/ttyS0",
  "/dev/ttyAMA2", #ESP-NOW
  "/dev/ttyAMA3",  
  "/dev/ttyAMA4",
  "/dev/ttyAMA5"  # LoRa
]
baudrate = 9600

[mqtt]
broker = "localhost"
port = 1883