version = 1
disable_existing_loggers = false

#
# Formatters
#
[formatters.simple]
format = "%(levelname)s: %(message)s"

[formatters.detailed]
format  = "[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s"
datefmt = "%Y-%m-%dT%H:%M:%S%z"

#
# Handlers
#
[handlers.console]
class     = "logging.StreamHandler"
level     = "DEBUG"
formatter = "simple"
stream    = "ext://sys.stderr"

[handlers.file]
class       = "logging.handlers.RotatingFileHandler"
level       = "DEBUG"
formatter   = "detailed"
filename    = "logs/bifrost.log"
maxBytes    = 50000
backupCount = 3

#
# Loggers
#
[loggers."protocols.mqtt_handler"]
level     = "DEBUG"
handlers  = ["console", "file"]
propagate = false

[loggers."protocols.serial_handler"]
level     = "DEBUG"
handlers  = ["console", "file"]
propagate = false

[loggers."utils.registry"]
level     = "DEBUG"
handlers  = ["console", "file"]
propagate = false

[loggers.root]
level    = "DEBUG"
handlers = ["console", "file"]